name: Check 3.x
on:
  push:
    branches:
      master

jobs:
  master:
    name: master check
    runs-on: [ubuntu-latest]
    env:
      SLACK_CHANNEL: android
    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Run LintCheck
        shell: bash
        run: ./gradlew detekt ktlintCheck assembleRelease
      - name: Run unit tests
        shell: bash
        run: ./gradlew --continue testRelease
      - name: Slack Notification
        if: failure()
        uses: homoluctus/slatify@master
        with:
          type: "failure"
          job_name: '*master Check*'
          username: GitHub
          channel: ${{env.SLACK_CHANNEL}}
          url: ${{ secrets.SLACK_WEB_HOOK }}
          commit: true
          token: ${{ secrets.GITHUB_TOKEN }}
